### ISSUE TITLE
Evento UserRegisteredHandler não é disparado

### ISSUE THREAD

**Issue by andrebaltieri** [andrebaltieri/room-booking#1]
RoomBooking.ApplicationService.Account.Handlers.UserRegisteredHandler

O evento **Handle** não está sendo disparado quando o usuário é registrado.

**Comment by andrebaltieri** [comment]
RoomBooking.ApplicationService.Account.Services.ApplicationService

OBS: Mesmo resolvendo manualmente não funciona: 

this._userRegisteredHandler = DomainEvent.Container.GetService<UserRegisteredHandler>();

**Comment by yanjustino** [comment]
Blz Verificando...

**Comment by yanjustino** [comment]
Resolvido o Handle esta sendo implementado pela interface IUserRegisteredHandler, contudo a Classe DomainEvents procura no container uma referencia explicita de IHandler<UserRegistered>. Apesar da Interface original estender de IHandler<UserRegistered> o Container não consegue resolver a dependência.

**Comment by andrebaltieri** [comment]
Entendi o ponto... queria resolver este cara não como um handler genérico, mas como um específico.
Vou criar uma melhoria para gente estudar melhor esta questão da resolução de dependências e do IContainer.
