### ISSUE TITLE
Sobre o SharedKernel

### ISSUE THREAD

**Issue by andrebaltieri** [andrebaltieri/room-booking#5]
Acho que distorcemos o conceito de SharedKernel neste exemplo... Lendo mais, entendi que o sharedkernel compartilha as entidades do domínio em sí, entre outros contexts, e no nosso caso, estamos usando ele para compartilhar coisas como IContainer.

Sugestão: Mover tudo que não for referente a domínio para o CrossCutting

**Comment by fabiobaptista** [comment]
Legal, ficariam apenas os contratos do repositório nesse momento?.

**Comment by yanjustino** [comment]
Não diria distorção. Na verdade seguimos uma linha Vernon.  dá uma olhada no exemplo dele (no link abaixo). Numa perspectiva de que o Shared Kernel são recursos que podem ser compartilhado entre times de projeto (diferentes), não sei se essa modelagem está tão errado assim... Até por que se vc pará pra pensar SC também tem o comportamento transversal... Outro exemplo de código é o  do próprio Eric Evans retirado do DDD Samples

(Vernon) https://github.com/VaughnVernon/IDDD_Samples_NET/tree/master/iddd_common
(Eric Evans) http://dddsample.sourceforge.net/xref/se/citerus/dddsample/domain/shared/package-summary.html

**Comment by fabiobaptista** [comment]
Bom dia pessoal,

Partindo do ponto que o Yan colocou, qual seria o fator de segregação para posicionamento dentro do SK ou CC?

**Comment by andrebaltieri** [comment]
Essa é a questão Fábio, acho que temos duas coisas para o mesmo fim aqui, ou misturamos algo... A maioria das coisas serão resolvidas no SharedKernel... para que o CrossCutting então?
Eu voto por mudar o nome CrossCutting para algo mais fixo, relativo apenas a Dependency Injection, já que só tem isso lá.

**Comment by fabiobaptista** [comment]
Faz realmente sentido a questão do eventos do domain estar SK, já que estão ligados, concordo que nesse ponto o CC ficaria em conflito, principalmente com a Infra. Podemos manter a implementação do DomainNotificationHandler na Infra e transformar o CC em DI como sua sugestão.

**Comment by kvnallen** [comment]
O CrossCutting por estar na camada de Infra, tem dependências de externas que talvez não fique interessante no SharedKernel, por exemplo o Unity. 

Vejo o SK como um domínio agnóstico compartilhado.

**Comment by fabriciorissetto** [comment]
Concordo com o André: "sharedkernel compartilha as entidades do domínio em sí". A meu ver o Shared Kernel deve representar um conceito para o domínio, e não apenas ser um container técnico. Acho que faz sentido ter um Shared Kernel quando vc tem diversos Bounded Contexts e quer compartilhar dados entre eles, ou seja, atravessar os limites do contexto. Outro benefício do SK é deixar uma visão clara do que é o "Core" das suas entidades.

Mas vendo os links que o Yan postou (inclusive um do próprio Evans) e fazendo mais algumas pesquisas notei que tem bastante gente colocando essas mesmas coisas ali no SK. Acho que no final das contas a escolha é por gosto. 

Eu particularmente prefiro colocar aquelas interfaces em uma DLL de helper (talvez aquela ali mesmo, só não chamaria de Shared Kernel). Além disso tem outras entidades que acho que se encaixam melhor na camada de infra, como a interface do UoW (moveria pra CrossCutting), o repositório genérico (que não parece estar sendo utilizado). 

Prefiro deixar fora do domínio o que não agrega valor a ele, como por exemplo a AssertionConcern, o uso dela tem valor no domínio, mas o conteúdo dela não.

Se acharem que algo disso faz sentido, me digam que eu posso alterar e fazer pull request. Se não acharem, não tem problema também, como disse, é questão de gosto. Nesse segundo caso, acho que a issue pode ser fechada.

**Comment by yanjustino** [comment]
Geralmente eu tenho feito a seguinte divisão.

```
Common
       |__ Domain.Model
       |        |__ Models
       |        |__ Application
       |
       |__ Data
       |    |__ ORM        
       |    |__ DataQuery
       |
       |__ ThirdParty
                |__ Tests        
                |__ Components
                |__ External        
```

**Comment by fabriciorissetto** [comment]
Não entendi Yan. Common seria um projeto e a segunda coluna da hierarquia seriam pastas? Não saquei a ideia.

**Comment by anjdric** [comment]
Geralmente utilizo a abordagem do SK em recursos de valor para domínios compartilhados, enquanto o CC para componentes mais estáticos de apoio que não venham corromper nenhum domínio.
