### ISSUE TITLE
Essa implementação do UnitOfWork é funcional ou é só ilustrativa?

### ISSUE THREAD

**Issue by legimenes** [andrebaltieri/room-booking#6]
É só uma dúvida, ok? Não sei se analisei corretamente mas nessa implementação não enxergo o momento que o contexto do UnitOfWork se "liga" com o contexto do Repositório para o commit das operações. Caso realmente vocês tenham apenas ilustrado a situação, então seria necessário no construtor do Repositório chegar mais um parâmetro que seria a interface do UoW e nesse momento setar o contexto do Repositório para o contexto da interface do UoW? Estaria correto este meu approach ou haveria outra forma mais elegante?

**Comment by yanjustino** [comment]
@leletronic essa implementação funciona sim. Você não está enxergando essa ligação por que ela ocorre por Injeção de dependência na camada de Crosscutting, onde utilizamos o Unity para resolver esta ligação. Lá está configurado da seguinte forma:

``` csharp
container.RegisterType<RoomBookingDataContext, RoomBookingDataContext>(new HierarchicalLifetimeManager());
container.RegisterType<IUnitOfWork, UnitOfWork>(new HierarchicalLifetimeManager());
container.RegisterType<IUserRepository, UserRepository>(new HierarchicalLifetimeManager());
```

Desse jeito, UnitOfWork e UserRepository apontam para o mesmo RoomBookingDataContext na mesma requisição!

**Comment by legimenes** [comment]
Boa @yanjustino!
Eu não havia me atentado à resolução do RoomBookingDataContext no Unity. Obrigado pela ajuda e pela atenção!

Abraços!
